version: '3.8'

services:
  pvz-service:
    build: .
    container_name: pvz-service
    ports:
      - "8080:8080"
      - "9000:8080"
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      pvz-db:
        condition: service_healthy
    networks:
      - pvz-network


  pvz-db:
    image: postgres:latest
    container_name: pvz-db
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - pvz-network

volumes:
  postgres_data:

networks:
  pvz-network:
    driver: bridge